services:
  - type: web
    name: chat-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chat-postgres
          property: connectionString
databases:
  - name: chat-postgres
    plan: free
    region: oregon
